# Generated by Django 5.2.5 on 2025-08-31 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='status',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='internship_offer',
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.intern')),
                ('internship_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.internshipoffer')),
            ],
            options={
                'unique_together': {('intern', 'internship_offer')},
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.internshipapplication'),
        ),
    ]
