# Generated by Django 5.2.5 on 2025-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
