# Generated by Django 5.2.5 on 2025-09-01 07:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_intern_status_remove_interview_intern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 1, 7, 50, 32, 337663, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
