# Generated by Django 5.2.5 on 2025-12-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internshipoffer_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='core.internshipapplication'),
        ),
    ]
